import type { Metadata } from 'next'
import './globals.css'
import 'leaflet/dist/leaflet.css'

import { Inter, Montserrat } from 'next/font/google'

const inter = Inter({ subsets: ['latin'], variable: '--font-inter' })

const montserrat = Montserrat({
    subsets: ['latin'],
    variable: '--font-montserrat',
})

export const metadata: Metadata = {
    title: 'Volna',
    description: 'Generated by create next app',
}

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode
}>) {
    return (
        <html
            lang='ua'
            className={`${inter.variable} ${montserrat.variable}`}>
            <body className={`antialiased`}>{children}</body>
        </html>
    )
}
